### ISSUE TITLE
Python Code for finding Binary of Any Number

### ISSUE THREAD

**Issue by destroyersworld007** [destroyersworld007/hacktoberfest_2021#1]
Here, you need to enter a code which can convert any number to binary.

**Comment by sohamm20** [comment]
Hello. I have made this program. Where can I submit it?

**Comment by sohamm20** [comment]
Here is my Code :

`

# Program to Convert any number to Binary

def binaryConversion(num):
     
    if num >= 1:
        binaryConversion(num // 2)
    print(num % 2, end = '')
 
# Test Code
     
# decimal value
dec_val = 24
     
# Calling function
binaryConversion(dec_val)

`

**Comment by sohamm20** [comment]
Here is my code :

```
# Program to Convert any number to Binary

def binaryConversion(num):
     
    if num >= 1:
        binaryConversion(num // 2)
    print(num % 2, end = '')
 
# Test Code
     
# decimal value
dec_val = 24
     
# Calling function
binaryConversion(dec_val)
```

**Comment by tausiq2003** [comment]
hello can I do this for hacktoberfest 2021

**Comment by tausiq2003** [comment]
@sohamm20 delete that screenshot please

**Comment by sohamm20** [comment]
> 
> 
> @sohamm20 delete that screenshot please

Done

**Comment by tausiq2003** [comment]
can I contribute

**Comment by Sans2326** [comment]
Hii, can I contribute I've worked on it

**Comment by rjkalash** [comment]
hello can it be assigned to me

**Comment by destroyersworld007** [comment]
i will open other issue for you all wait for sometime

**Comment by tausiq2003** [comment]
please assign to me for this task

**Comment by destroyersworld007** [comment]
check the new issue
